### ISSUE TITLE
NameError: name 'reload' is not defined

### ISSUE THREAD

**Issue by kblocat** [WebShark025/TheZigZagProject#1]
Hi, i'm trying to execute the bot using the launch.sh, but it shows me an error:

$ ./launch.sh
(SO DANGEROUS) Do you want to use auto launch? (to kill it=HOLD Ctrl+C) y

Traceback (most recent call last):
  File "bot.py", line 22, in <module>
    reload(sys)
NameError: name 'reload' is not defined
Bot has crashed! Launching it again.
Traceback (most recent call last):
  File "bot.py", line 22, in <module>
    reload(sys)

What should i do to solve this isse ?

Regards,

**Comment by WebShark025** [comment]
Bug fxed. Use git pull to update
Note that
1) this project is written in python2.7 and not python 3 
2) its also abandoned and wont be continued anymore, so use it on your own risk.
